### ISSUE TITLE
flocx_market put contract api is not working

### ISSUE THREAD

**Issue by DanNiESh** [CCI-MOC/flocx-market#107]
When I want to make a put request to marketplace contract, the flocx-market app returns error: save() missing 1 required positional argument: 'context'. 
I think it's because the code here: https://github.com/CCI-MOC/flocx-market/blob/ac7562e0780159417118e826e2d69048d34af66a/flocx_market/api/contract.py#L46 doesn't pass the parameter 'context' in to save() method. Probably the same issue with delete api and the api in bid.py.

**Comment by DanNiESh** [comment]
@fvukelic

**Comment by tzumainn** [comment]
Ah, yep, this is from something that @ljmcgann is working on. Leo, could you update your followup PR to update the contract business object?

**Comment by ljmcgann** [comment]
The importance of unit testing with assert_called_with instead of assert_called_once I suppose

**Comment by ljmcgann** [comment]
I have updated the pr

**Comment by tzumainn** [comment]
This should be fixed now then! @DanNiESh can you try it, and close this issue if it works?

**Comment by DanNiESh** [comment]
Thanks! It works.
