### ISSUE TITLE
We should be using .one (or .one_or_none) instead of .first in the database api

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/flocx-market#111]
Many of our database api `get` operations using the `.first()` filter on queries, but this inappropriate: if the query returns more than a single result, something is wrong.

**Comment by ljmcgann** [comment]
So we do not want to raise errors in get?

**Comment by larsks** [comment]
I don't know! We aren't *currently*; we're just returning `None` if there are no matches.

**Comment by tzumainn** [comment]
I think we want to raise errors; but after this code merges, we'll just see if a `get` returns None, and if so, throw an exception.
