### ISSUE TITLE
server_id should not be unique

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/flocx-market#50]
attempting to create an offer with the same server_id as an existing offer will fail:

```
E       sqlalchemy.exc.IntegrityError: ... UNIQUE constraint failed: offers.server_id
```

It should be possible create multiple offers from a server as long as they don't overlap in time.

**Comment by larsks** [comment]
So @tzumainn here's a question:

If have multiple offers for the same server, does each offer contain the hardware specs separately? Or do we need a `Server` object to hold the hardware specs, which we then reference from each offer?

**Comment by tzumainn** [comment]
Ugh, good question. At a certain point is the real answer something like federated ironic or something?
